[package]
name = "toylang"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = {version = "0.22.0", features = ["lexer"]}
lazy_static = "1.5.0"

[build-dependencies]
lalrpop = {version = "0.22.0"}

